"""Conservative post-processing for narration generated by Kokoro."""
from __future__ import annotations

import subprocess
from pathlib import Path


def polish(input_path: str, output_path: str) -> str:
    """Normalize and gently compress narration without synthetic over-processing."""
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "ffmpeg", "-y", "-loglevel", "error", "-i", input_path,
            "-af", "highpass=f=70,acompressor=threshold=-18dB:ratio=2:attack=20:release=120:makeup=1,loudnorm=I=-16:TP=-1.5:LRA=11",
            "-codec:a", "libmp3lame", "-b:a", "192k", output_path,
        ],
        check=True,
    )
    return output_path
